add registry tweaks

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,7 +17,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program. If not see <http://www.gnu.org/licenses/gpl.html>
 
-#TODO: Registry tweaks: date format, font size, default mail (under wine)
+#TODO: Registry tweaks: default mail (under wine)
 
 #FIXME: Edit eudora.sh post-install, hardcoding correct prefix, exec and data
 # paths, reading from registry
@@ -42,6 +42,10 @@ urlpdf=http://www.eudora.com/download/eudora/windows/7.1/Eudora_71_User_Manual.p
 # drive letters to add
 drives=()
 
+# Registry tweaks
+dpi=96      # Font DPI ("size")
+intldate=0  # "International" Date/Time format: leading zeros, 24h, dd/mm/YYYY
+
 # leave these ones alone
 logout=1  # install changes this to 0 if exec dir is already in PATH
 verbose=1
@@ -52,14 +56,16 @@ uninstall=0
 
 myname="${0##*/}"
 mydir=$(dirname "$(readlink -f "$0")")
-greenC=$(tput setaf 2)
+greenC=$(tput setaf 2; tput bold)
 redC=$(tput setaf 1; tput bold)
 endC=$(tput sgr0)
 
 fatal()   { [[ "$1" ]] && echo "${redC}$myname: error: $1${endC}" >&2; exit ${2:-1}; }
-invalid() { echo "$myname: invalid option: $1" >&2 ; usage 1 ; }
-missing() { echo "$myname: missing ${1:+$1 }operand" >&2 ; usage 1 ; }
-message() { ((verbose)) && echo "${greenC}* ${1}${endC}" ; }
+argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
+invalid() { argerr "invalid option: $1" ; }
+missing() { argerr "missing ${1:+$1 }operand." ; }
+integer() { [[ "$1" != *[!0-9]* ]] || argerr "'$1'${2:+ in $2} is not an integer."; }
+message() { ((verbose)) && echo "${greenC}*${endC} ${1}" ; }
 quit()    { ((verbose)) && echo "Goodbye!" ; exit; }
 
 usage() {
@@ -122,15 +128,18 @@ while (( $# )); do
 	case "$1" in
 	-h|--help     ) usage                ;;
 	-q|--quiet    ) verbose=0            ;;
+	--intl-date   ) intldate=1           ;;
 	--name=*      ) name="${1#*=}"       ;;
 	--exec=*      ) exec="${1#*=}"       ;;
 	--prefix=*    ) prefix="${1#*=}"     ;;
 	--installer=* ) tarball="${1#*=}"    ;;
+	--dpi=*       ) dpi="${1#*=}"        ;;
 	--drive=*     ) drives+=("${1#*=}")  ;;
 	--name        ) shift; name="$1"     ;;
 	--exec        ) shift; exec="$1"     ;;
 	--prefix      ) shift; prefix="$1"   ;;
 	--installer   ) shift; tarball="$1"  ;;
+	--dpi         ) shift; dpi="$1"      ;;
 	--drive       ) shift; drives+=("$1");;
 	--uninstall   ) uninstall=1          ;;
 	--            ) shift; tarball="$1"
@@ -144,7 +153,7 @@ done
 [[ "$name" ]] || missing "name"
 [[ "$exec" ]] || missing "exec"
 [[ "$tarball" && ! -f "$tarball" ]] && invalid "installer '$tarball' was not found"
-
+integer "$dpi" "--dpi"
 
 for drive in "${drives[@]}"; do
 	IFS=: read drive_letter drive_path <<< "$drive"
@@ -468,6 +477,32 @@ if ((logout)); then
 	    PATH="\$HOME/$relexecdir:\$PATH"
 	fi
 	EOF
+fi
+
+
+# Registry tweaks
+regfile="$deskdir/$exec.reg"
+
+if ((dpi != 96)); then
+	message "adjusting font size to $dpi dpi"
+	dpihex=$(printf '%08x' "$dpi")
+	cat >> "$regfile" <<-REGEDIT
+	[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Hardware Profiles\Current\Software\Fonts]
+	"LogPixels"=dword:$dpihex
+	REGEDIT
+fi
+if ((intldate)); then
+	message "adjusting date and time format"
+	cat >> "$regfile" <<-REGEDIT
+	[HKEY_CURRENT_USER\Control Panel\International]
+	"iTime"="1"
+	"iTLZero"="1"
+	"sShortDate"="dd/MM/yyyy"
+	REGEDIT
+fi
+
+if [[ -f "$regfile" ]]; then
+	env WINEPREFIX="$dir" wine regedit "$regfile" 2>&3
 fi
 
 
