remove old cruft

diff --git a/install b/install
--- a/install
+++ b/install
@@ -192,13 +192,6 @@ execfile=${deskdir}/${exec}
 			esac
 		}
 
-		message "Successfully uninstalled $name"
-		# UNINSTALL
-
-		#! /bin/bash
-
-		# Add Eudora to list of mail handlers in Menu > Preferences > Prefered Applications
-
 		# Launcher
 		rm -f "$HOME/bin/eudora"
 
@@ -210,15 +203,9 @@ execfile=${deskdir}/${exec}
 		# Desktop
 		rm -f "$HOME/.local/share/applications/eudora.desktop"
 
-		# Prefered Applications list
-		sudo rm -f "/usr/share/gnome-control-center/default-apps/eudora.xml"
-
-		# URI Handler
-		#gconftool -t string -s /desktop/gnome/url-handlers/mailto/command 'eudora %s'
-		#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/needs_terminal false
-		#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/enabled true
-
 		find "$HOME"/.local/share -type d -empty -delete
+
+		message "Successfully uninstalled $name"
 	;;
 	esac
 
@@ -285,7 +272,7 @@ execfile=${deskdir}/${exec}
 	read -r -p "$msg (yes,NO): " confirm
 	case "$confirm" in
 	[Yy]*) message "removing $dir" ;
-	       $sudo rm -rf "$deskdir" || fatal "could not remove $dir" ;; ####### REPLACE DESKDIR TO DIR!!!
+	       $sudo rm -rf "$dir" || fatal "could not remove $dir" ;;
 	    *) quit
 	esac
 }
@@ -397,26 +384,3 @@ $sudo chmod +x "$deskdir"/* ||
 message ""
 message "Succesfully installed ${name}!"
 ((logout)) && echo "Log out for changes to apply..."
-
-exit
-
-#! /bin/bash
-
-# Add Eudora to list of mail handlers in Menu > Preferences > Prefered Applications
-# Prefered Applications list
-#sudo cp --no-preserve=mode,ownership "$BASEDIR/eudora.xml" "/usr/share/gnome-control-center/default-apps/"
-
-# URI Handler
-#gconftool -t string -s /desktop/gnome/url-handlers/mailto/command 'eudora %s'
-#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/needs_terminal false
-#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/enabled true
-
-# Eudora settings
-#dir="/home/rodrigo/.local/share/wineprefixes/eudora/drive_c/Program Files/Qualcomm/Eudora"
-#cp "$dir/extrastuff/esoteric.epi" "$dir/"
-
-# TODO:
-# - import regisstry key
-# - edit ~/.local/share/applications/mimeapps.list
-# [Default Applications]
-#x-scheme-handler/mailto=eudora.desktop
